### ISSUE TITLE
修正1

### ISSUE THREAD

**Issue by jampanman-git** [Ryohei-12/poker_looking_back#6]
<修正点>
○routes/web.php
・ハンドレンジ系のルーティングはgroup使ってまとめた方が見やすい
**→グルーピング済、ついでに投稿系のルーティングもグループ化した**
・40行目
「CRAD可能」→「CRUD可能」に変更
Uはアップテートの頭文字であるため。
**→変更済**
・59行目
個人的な趣向にはなるけども、できればユーザー認証を1番上か下に持っていってくれたら見やすいと感じる。
**→修正済、一番上に持ってきた**

○app/Http/Requests/ArticleRequest.php
30行目 不要
**→削除済**

○app/Http/Controllers/Auth/ForgotPasswordController.php
30行目~32行目
行が空いているのが気になる
**→空行削除済**

○app/Http/Controllers/ArticleController.php
・23行目 create→sreate
**→済（createに修正）**
・全体的にコメントアウトこんなに細かくなくていいかも。
ex)23行目 「投稿画面遷移」
28行目 「新規投稿処理」
→特段の事情がなければ細かくコメント書かなくて良いと感じる
**→指定ファイルに 「投稿画面遷移」の記述なし、bladeファイルのことでしょうか。
 「新規投稿処理」は削除済み**

○app/Http/Controllers/CommentsController.php
全体的にコメントアウトこんなに細かくなくていいかも。
ex)14,15行目 不要
**→削除済み**

○app/Http/Controllers/UserController.php 
全体的にコメントアウトこんなに細かくなくていいかも。
**→簡略化済み**

○app/Providers/RouteServiceProvider.php
26,42行目 不要
**→削除済み**

○モデル
・モデルがModelディレクトリに入ってない…笑
コントローラーみたいな形で入れよう。
**→Modelディレクトリ作成、それぞれModelディレクトリに移動するとブラウザでエラー発生するため移動はまだしていない、たぶんコントローラーに場所指定してないからか。。**
・$fillableを使っているならば$guardedや$primaryKey等を使用したい。
**→済**

○app/User.php 
$fillableと$hiddenのカラム名を改行した方が他のファイルと統一感が出ると感じる。
**→改行済**

○マイグレーションファイル全般
user_idカラムにonDelete('cascade')をつけよう。
そうすればユーザーが削除された時にも関連するデータが一掃される。
**→articleテーブルとcommentテーブルで一応cascadeの設定はしているが、、マイグレーションファイルを編集して良いのだろうか。
また、新たに変更としてマイグレイトするのがこの場合正しいのだろうか。**

**Comment by Ryohei-12** [comment]
コメントに追記という形で行ったことメモしました。
Modelディレクトリとマイグレーションファイル、グルーピングについて質問したいので明日電話させてください。

▼質問内容
①Modelについて
作成したModelディレクトリにModel達を入れると、
「include .... failed to open stream: No such file or directory」や、「許可されていないアクション」といったエラーが発生する。
原因と対策を確認したいです。

②マイグレーションファイルのcascadeを修正するだけではデータ構造として修正できていないのではないか？
ここでは面接官に見せるためにマイグレーションファイルを修正して、mysqlでは直接操作で変更を加えるということでしょうか。

③グルーピングによる不具合について
もしかすると①の原因がこれかもしれない
合わせて確認させてください。
