### ISSUE TITLE
修正2

### ISSUE THREAD

**Issue by jampanman-git** [Ryohei-12/poker_looking_back#8]
コメントアウトってこの前変更した時に戻した？笑
コントローラーとかが前回issueの修正前に戻っている気がする。

○routes/web.php
「→ログインユーザーのみ」不要

○マイグレーションファイル全般
コメントアウトあるところとないところがあるので統一したい。
また、downの時にマイグレーション書いているのは意図がある感じ？

○app/Http/Controllers/ArticleController.php 
34行目 リダイレクト先のパス指定がここだけrouteではないので統一したい。
コメントの抽象化

○app/Http/Controllers/CommentsController.php
コメントの抽象化

○app/Http/Controllers/UserController.php 
コメントの抽象化
10行目 「ユーザー情報取得」だけでいいかも。

○app/Mail/BareMail.php
コメントアウトのインデントがズレてる

○app/Article.php 
コメントの抽象化

○resources/views/app.blade.php
36~38行目 インデントずれてる

○ビュー全般
styleをcssファイルに持ってくる

○resources/views/top.blade.php
画像を絶対パスにする。
また、ここだけheadあるのは意図がある？

**Comment by Ryohei-12** [comment]
○resources/views/top.blade.php
解決

**Comment by Ryohei-12** [comment]
▼残り
①各ブレードファイルにCSSの設定
　└app.bladeに何かしら設定してから、各ページごとのcssファイル作成
　　→4/29以内
②マイグレーションファイル修正

**Comment by Ryohei-12** [comment]
CSS設定完了

**Comment by Ryohei-12** [comment]
ブレードファイルにCSS設定、マイグレーションファイルの修正ともに完了。
テストコード開始
